# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/UTN/3er/TD1/TP/TP_Final_Bank_Valeria/TP_Final_Bank_Valeria.srcs/sources_1/ip/ramMem/ramMem.xci
# IP: The module: 'ramMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/UTN/3er/TD1/TP/TP_Final_Bank_Valeria/TP_Final_Bank_Valeria.gen/sources_1/ip/ramMem/ramMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ramMem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/UTN/3er/TD1/TP/TP_Final_Bank_Valeria/TP_Final_Bank_Valeria.srcs/sources_1/ip/ramMem/ramMem.xci
# IP: The module: 'ramMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/UTN/3er/TD1/TP/TP_Final_Bank_Valeria/TP_Final_Bank_Valeria.gen/sources_1/ip/ramMem/ramMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ramMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
